version: "3.3"
services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: access-key
      MINIO_SECRET_KEY: it-is-my-super-secret-key
    entrypoint: sh
    command: -c 'mkdir -p doc_gen_minio/export/clickhouse && minio server doc_gen_minio/export'
    ports:
      - 9010:9000
    networks:
      - clickhouse-backup

  clickhouse:
    image: yandex/clickhouse-server:19.15.3.6
    container_name: clickhouse
    environment:
      TZ: UTC
    volumes:
      - ../clickhouse-backup/clickhouse-backup:/usr/bin/clickhouse-backup
      - ./config.yml:/etc/clickhouse-backup/config.yml
    ports:
      - 9000:9000
    networks:
      - clickhouse-backup

networks:
  clickhouse-backup:
